import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>WhiXard </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to WhiXard&apos;s Portfolio
        </h1>

        <p className={styles.description}>
          This is a simple page, just for making a simple contact page
        </p>

        <div className={styles.grid}>
          <a href="https://t.me/WhiXard" className={styles.card}>
            <h2>Telegram &rarr;</h2>
            <p>This is my Telegram contact, i&apos;m PM friendly so poke me if you want</p>
          </a>

          <a href="https://jellyfin.buffolollo.it" className={styles.card}>
            <h2>Discord &rarr;</h2>
            <p>My Discord Tag is: wisard#4611, same thing as Telegram</p>
          </a>

          <a
            href="https://github.com/Bildcraft1"
            className={styles.card}
          >
            <h2>Github &rarr;</h2>
            <p>Here you can see my programming stuff (Yeah my code sucks hahah)</p>
          </a>

          <a
            href="https://plugins.whixonio.net"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Other Site &rarr;</h2>
            <p>
              Another website i made using Next.Js and TailwandCSS
            </p>
          </a>

          <a
            href="/api/gpg"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>GPG Key &rarr;</h2>
            <p>
              Here you can find my GPG key that i use for mails and commits
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
